version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: floodwatch-pro
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development 